### ISSUE TITLE
why abb ibr1410 is not supported?

### ISSUE THREAD

**Issue by Onlyfd** [ros-industrial/abb#189]

**Comment by gavanderhoorn** [comment]
If you're asking whether `abb_driver` (and/or `abb_robot_driver`) support the IRB 1410, then the answer would be: those packages are largely manipulator-agnostic, so there is nothing "to support". It should just work.

If you're asking why there are no support and MoveIt package for that specific series/variant, the answer would be: because no one created one.

"support" for a particular series or variant mostly comes down to creating a support package (which provides the meshes, `.launch` and `.xacro` files).

If you'd like to create a support package, I could provide some assistance in the form of reviewing it (ie: making sure it's correct).

You could refer to [abb_crb15000_support](https://github.com/ros-industrial/abb_experimental/tree/6629b1694687a182a586423d06bb9921a00b0fcb/abb_crb15000_support) for an example.

Meshes can be downloaded from the ABB website. The kinematic structure can be found in the respective datasheet.

**Comment by gavanderhoorn** [comment]
As this is not an issue with the packages currently in this repository, I've closed it.

That does not mean you can't comment on it any more of course.
