### ISSUE TITLE
Production Support for GoFa CRB 15000

### ISSUE THREAD

**Issue by DaveBGld** [ros-industrial/abb#197]
I see that GoFa CRB 15000 is supported in the abb_experimental.

Is there production support for it? We are considering buying a few to integrate into our ROS based solution, but would not without production grade ROS support.

Many thanks!

**Comment by gonzalocasas** [comment]
What does production-grade support mean? The urdf model for it is correct, we use it on our GoFas. That's as far as it goes in terms of what this repository offers for the GoFa robot.

This repo does not provide control/drivers though, for that we use [compas_rrc](https://github.com/compas-rrc/compas_rrc/) but only because we also develop that, I believe the driver provided by ROS-I also works well on GoFas.
