### ISSUE TITLE
ABB driver locks up after stop command sent

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/abb#42]
See detailed write-up on google code [here](https://code.google.com/p/swri-ros-pkg/issues/detail?id=67).

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, I believe I have tracked down what is causing the driver to lock up. When ROS sends the stop command to the abb driver, it does so using the sendAndReceivedMsg function part of the smpl_msg_connection which it is expecting a reply from the abb driver which it never receives. The reason it never receives the a reply is because the message comm_type is SERVICE_REQUEST and on the abb driver side it is looking for comm_type SERVICE_REPLY to send a reply message. If I make the change bellow in the abb driver is solves the issue, but I am not familiar enough with ROS to know if this is the correct fix. Your thoughts? 

! send reply, if requested
    !IF (message.header.comm_type = ROS_COM_TYPE_SRV_REPLY) THEN
    IF (message.header.comm_type = ROS_COM_TYPE_SRV_REQ) THEN  
        reply_msg.header := [ROS_MSG_TYPE_JOINT_TRAJ_PT, ROS_COM_TYPE_SRV_REPLY, ROS_REPLY_TYPE_SUCCESS];
        ROS_send_msg client_socket, reply_msg;
    ENDIF

**Comment by shaun-edwards** [comment]
I'd have to see this in context to be certain, but this seems correct.  I'm curious if the stop command is handled differently from other motion types (i.e. waypoints).  Any motion command should be of type `SRV_REQ` and thus block until the controller sends a reply.

**Comment by Levi-Armstrong** [comment]
I took a look at how the joint trajectory is sent to the robot which is done by the function JointTrajectoryDownloader::send_to_robot in joint_trajectory_downloader.cpp. It is only using the sendMsg function and it checks that this function return true, it does not wait for a reply message form the controller.

**Comment by Levi-Armstrong** [comment]
If the points are sent to the robot using the JointTrajectoryStreamer::send_to_robot function in joint_trajectory_streamer.cpp, it sends the points using the sendAndReveiveMsg function which would cause the abb drivers to lock up. MoveIt is sending the points to the robot using the JointTrajectoryDownloader::send_to_robot so this is why it was able to send the points without locking up. I believe based on your comment and these findings that the JointTrajectoryDownloader::send_to_robot should be using the sendAndReveiveMsg function instead sendMsg function along with change to the abb driver.

**Comment by shaun-edwards** [comment]
@Levi-Armstrong, I looked into things a little bit more.  It could be that @JeremyZoss implemented the trajectory downloading without responses on purpose in order to improve performance.  Since the trajectory downloader uses TCP sockets, the point should arrive as expected.  The only reason for a response is to verify that this is the case (not required) or to synchronize the controller (maybe not required).  Not sure if this offers any clarity.

**Comment by shaun-edwards** [comment]
Addressed by PR #62
